project_id = "sovetydoma"

[auth]
site_url = "https://1001sovet.ru"
additional_redirect_urls = [
  "https://1001sovet.ru/**",
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**",
]

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.email.template.confirmation]
subject = "SovetyDoma: confirm your email"
content_path = "./supabase/templates/confirmation.html"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
