import type { ContentData } from './types'
// Generated by scripts/build-content.mjs (pnpm run content) before dev/build.
import raw from './data/articles.json'

export const content = raw as ContentData

const SITE = 'https://1001sovet.ru'

// Article images are stored on the main site; mini-app bundles only metadata.
export function imageUrl(image: string): string {
  if (!image) return ''
  if (/^https?:\/\//.test(image)) return image
  return `${SITE}${image.startsWith('/') ? '' : '/'}${image}`
}

export function articlesByCategory(slug: string): import('./types').Article[] {
  return content.articles.filter((a) => a.category === slug)
}
