'use client'

import { useState } from 'react'

interface QueueItem {
  id: string
  platform: 'vk' | 'fb'
  event_type: 'comment' | 'message'
  incoming_text: string | null
  draft_reply: string | null
  status: string
  created_at: string
}

const API = process.env.NEXT_PUBLIC_SUBSCRIPTIONS_API_URL || 'https://sovetydoma-subscriptions.filippmiller.workers.dev'

/**
 * Review queue for the social responder. Drafts are generated by the worker and
 * held here — NOTHING is posted to VK/FB until an admin clicks "Отправить".
 * The worker admin endpoints are gated by x-admin-key (ADMIN_API_KEY).
 */
export default function AdminResponder() {
  const [adminKey, setAdminKey] = useState('')
  const [items, setItems] = useState<QueueItem[]>([])
  const [edits, setEdits] = useState<Record<string, string>>({})
  const [busy, setBusy] = useState('')
  const [msg, setMsg] = useState('')

  async function load() {
    setMsg('')
    try {
      const res = await fetch(`${API}/admin/responder/list?status=pending_review`, { headers: { 'x-admin-key': adminKey } })
      const data = await res.json()
      if (!res.ok || !data.ok) { setMsg(`Ошибка: ${data.error || res.status}`); return }
      setItems(data.items || [])
      setEdits(Object.fromEntries((data.items || []).map((i: QueueItem) => [i.id, i.draft_reply || ''])))
    } catch (e) { setMsg(`Ошибка сети: ${String(e)}`) }
  }

  async function act(id: string, kind: 'send' | 'skip') {
    setBusy(id)
    setMsg('')
    try {
      const body = kind === 'send' ? { id, text: edits[id] } : { id }
      const res = await fetch(`${API}/admin/responder/${kind}`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'x-admin-key': adminKey },
        body: JSON.stringify(body),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) { setMsg(`${id}: ${data.error || res.status}`) }
      else setItems((prev) => prev.filter((i) => i.id !== id))
    } catch (e) { setMsg(`Ошибка сети: ${String(e)}`) }
    finally { setBusy('') }
  }

  return (
    <div style={{ maxWidth: 820, margin: '0 auto', padding: '1rem' }}>
      <h1 style={{ fontSize: '1.4rem', fontWeight: 800 }}>Ответчик — очередь на ревью</h1>
      <p style={{ color: '#666', fontSize: '0.9rem' }}>
        Черновики ответов на комментарии/сообщения VK и FB. Ничего не публикуется, пока вы не нажмёте «Отправить».
      </p>
      <div style={{ display: 'flex', gap: '0.5rem', margin: '1rem 0' }}>
        <input
          type="password" value={adminKey} onChange={(e) => setAdminKey(e.target.value)}
          placeholder="x-admin-key" style={{ flex: 1, padding: '0.5rem', border: '1px solid #ccc', borderRadius: 6 }}
        />
        <button onClick={load} style={btn}>Загрузить</button>
      </div>
      {msg && <p style={{ color: '#c0392b' }}>{msg}</p>}
      {items.length === 0 && <p style={{ color: '#999' }}>Очередь пуста.</p>}
      {items.map((it) => (
        <div key={it.id} style={{ border: '1px solid #e6ddd2', borderRadius: 10, padding: '1rem', marginBottom: '1rem', background: '#fbf8f4' }}>
          <div style={{ fontSize: '0.78rem', color: '#8a7', fontWeight: 700, textTransform: 'uppercase' }}>
            {it.platform} · {it.event_type === 'comment' ? 'комментарий' : 'сообщение'}
          </div>
          <p style={{ margin: '0.4rem 0', whiteSpace: 'pre-wrap' }}><b>Входящее:</b> {it.incoming_text || '—'}</p>
          <textarea
            value={edits[it.id] ?? ''} onChange={(e) => setEdits((p) => ({ ...p, [it.id]: e.target.value }))}
            rows={3} style={{ width: '100%', padding: '0.5rem', border: '1px solid #d9cdbf', borderRadius: 6, fontFamily: 'inherit' }}
          />
          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
            <button disabled={busy === it.id || !edits[it.id]?.trim()} onClick={() => act(it.id, 'send')} style={{ ...btn, background: '#1e8449' }}>
              {busy === it.id ? '…' : 'Отправить'}
            </button>
            <button disabled={busy === it.id} onClick={() => act(it.id, 'skip')} style={{ ...btn, background: '#999' }}>Пропустить</button>
          </div>
        </div>
      ))}
    </div>
  )
}

const btn: React.CSSProperties = {
  background: '#c0392b', color: '#fff', border: 'none', borderRadius: 7,
  padding: '0.5rem 1rem', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit',
}
