# Extract runtime-injected CSS string literals from Next.js JS chunks.
# The site styles its header/layout/TOC/related blocks via styled-jsx, which only
# injects CSS at hydration. The renderer worker strips JS from dynamic pages, so we
# bake this CSS into the worker (workers/renderer/src/bakedCss.ts). Re-run after
# header/layout component changes:
#   python scripts/matrix/extract-styled-css.py
import glob
import json
import re
import sys
import urllib.request

sys.stdout.reconfigure(encoding="utf-8")

SITE = "https://1001sovet.ru"
TEMPLATE = SITE + "/ekonomiya/ekonomiya-vody/"
PROBES = [
    "site-header", "header-main-row", "article-layout", "article-main",
    "toc-sidebar", "toc-inline", "related-articles", "site-footer",
    "article-action-summary", "breadcrumbs",
]

html = urllib.request.urlopen(TEMPLATE).read().decode("utf-8")
chunk_urls = sorted(set(re.findall(r"/_next/static/chunks/[A-Za-z0-9._~-]+\.js", html)))
print(f"chunks: {len(chunk_urls)}")

def string_literals(src):
    # double-quoted, single-quoted and backtick literals
    for pat in (r'"((?:[^"\\\n]|\\.)*)"', r"'((?:[^'\\\n]|\\.)*)'", r"`((?:[^`\\]|\\.)*)`"):
        for m in re.finditer(pat, src):
            yield m.group(1)

def looks_like_css(text):
    if len(text) < 80 or "{" not in text or ":" not in text or ";" not in text:
        return False
    return any(p in text for p in PROBES)

found = {}
for u in chunk_urls:
    src = urllib.request.urlopen(SITE + u).read().decode("utf-8", errors="replace")
    for lit in string_literals(src):
        if not looks_like_css(lit):
            continue
        try:
            decoded = json.loads('"' + lit.replace('"', '\\"') + '"')
        except Exception:
            decoded = lit
        found[decoded] = u

css = "\n".join(found.keys())
# de-scope styled-jsx hash classes so the CSS survives future builds
css = re.sub(r"\.jsx-[0-9a-f]+", "", css)
out = "workers/renderer/src/bakedCss.ts"
banner = (
    "// GENERATED by scripts/matrix/extract-styled-css.py — do not edit by hand.\n"
    "// Runtime-injected styled-jsx CSS (header etc.) baked in because dynamic pages strip JS.\n"
    "export const BAKED_CSS: string = "
)
open(out, "w", encoding="utf-8", newline="\n").write(banner + json.dumps(css) + "\n")
print(f"literals: {len(found)}  css bytes: {len(css)} -> {out}")
for p in PROBES:
    print(f"  {p}: {p in css}")
