'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { CATEGORIES } from '@/lib/categories'
import { CATEGORY_EMOJI } from '@/lib/utils'
import { searchArticles, type ScoredArticle, type SearchableArticle } from '@/lib/search'

// Public static index (public/search-index-static.json, generated by
// scripts/generate-search-index-static.mjs) covers the 486 build-time MDX
// articles. The dynamic index (workers/renderer's /api/search-index.json,
// see SearchClient.tsx for the sibling implementation on /search/) covers
// everything published via the no-redeploy pipeline. Both are fetched lazily
// on first focus — not on every page load — and cached at module scope so
// navigating between pages doesn't refetch.
const STATIC_INDEX_URL = '/search-index-static.json'
const DYNAMIC_INDEX_URL = 'https://sovetydoma-renderer.filippmiller.workers.dev/api/search-index.json'
const MAX_SUGGESTIONS = 8

let cachedIndexPromise: Promise<SearchableArticle[]> | null = null

function loadIndex(): Promise<SearchableArticle[]> {
  if (!cachedIndexPromise) {
    cachedIndexPromise = Promise.all([
      fetch(STATIC_INDEX_URL).then((r) => (r.ok ? r.json() : [])).catch(() => []),
      fetch(DYNAMIC_INDEX_URL).then((r) => (r.ok ? r.json() : [])).catch(() => []),
    ]).then(([staticRows, dynamicRows]: [SearchableArticle[], Array<Omit<SearchableArticle, 'categoryName'>>]) => {
      const dynamicWithNames = dynamicRows.map((r) => ({
        ...r,
        categoryName: CATEGORIES[r.category]?.name ?? r.category,
      }))
      const staticSlugs = new Set(staticRows.map((a) => a.slug))
      return [...staticRows, ...dynamicWithNames.filter((r) => !staticSlugs.has(r.slug))]
    })
  }
  return cachedIndexPromise
}

export default function HeaderSearchAutocomplete() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<ScoredArticle<SearchableArticle>[]>([])
  const [open, setOpen] = useState(false)
  const [activeIndex, setActiveIndex] = useState(-1)
  const wrapRef = useRef<HTMLDivElement>(null)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    function onOutsideClick(e: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onOutsideClick)
    return () => document.removeEventListener('mousedown', onOutsideClick)
  }, [])

  useEffect(() => {
    const q = query.trim()
    if (q.length < 2) return
    if (timerRef.current) clearTimeout(timerRef.current)
    timerRef.current = setTimeout(() => {
      loadIndex().then((index) => {
        setResults(searchArticles(index, q, MAX_SUGGESTIONS))
        setOpen(true)
        setActiveIndex(-1)
      })
    }, 150)
    return () => { if (timerRef.current) clearTimeout(timerRef.current) }
  }, [query])

  function handleChange(value: string) {
    setQuery(value)
    if (value.trim().length < 2) {
      if (timerRef.current) clearTimeout(timerRef.current)
      setResults([])
      setOpen(false)
    }
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (!open || results.length === 0) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setActiveIndex((i) => (i + 1) % results.length)
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setActiveIndex((i) => (i <= 0 ? results.length - 1 : i - 1))
    } else if (e.key === 'Escape') {
      setOpen(false)
    } else if (e.key === 'Enter' && activeIndex >= 0) {
      e.preventDefault()
      const r = results[activeIndex]
      window.location.href = `/${r.category}/${r.slug}/`
    }
  }

  return (
    <div ref={wrapRef} style={{ position: 'relative', flex: 1, minWidth: 0 }}>
      <input
        type="search"
        name="q"
        placeholder="Найти совет..."
        aria-label="Поиск по статьям"
        autoComplete="off"
        role="combobox"
        aria-expanded={open}
        aria-autocomplete="list"
        aria-controls="header-search-listbox"
        value={query}
        onChange={(e) => handleChange(e.target.value)}
        onFocus={() => { if (results.length > 0) setOpen(true) }}
        onKeyDown={handleKeyDown}
        style={{ width: '100%' }}
      />
      {open && results.length > 0 && (
        <ul
          id="header-search-listbox"
          role="listbox"
          style={{
            position: 'absolute', top: 'calc(100% + 4px)', left: 0, right: 0,
            background: 'var(--bg-card, #fff)', border: '1px solid var(--border-color, #e2ddd3)',
            borderRadius: '10px', boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
            listStyle: 'none', margin: 0, padding: '0.4rem', zIndex: 50,
            maxHeight: '70vh', overflowY: 'auto',
          }}
        >
          {results.map((r, i) => (
            <li key={`${r.category}-${r.slug}`} role="option" aria-selected={i === activeIndex}>
              <Link
                href={`/${r.category}/${r.slug}/`}
                onMouseDown={() => setOpen(false)}
                style={{
                  display: 'flex', gap: '0.6rem', alignItems: 'flex-start', padding: '0.5rem 0.6rem',
                  borderRadius: '8px', textDecoration: 'none', color: 'inherit',
                  background: i === activeIndex ? 'rgba(0,0,0,0.05)' : 'transparent',
                }}
              >
                <span aria-hidden="true">{CATEGORY_EMOJI[r.category] || '📄'}</span>
                <span style={{ minWidth: 0 }}>
                  <span style={{ display: 'block', fontSize: '0.9rem', fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {r.title}
                  </span>
                  <span style={{ display: 'block', fontSize: '0.75rem', color: '#888' }}>{r.categoryName}</span>
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
